import { useGetConfig } from "@/lib/api-client-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Link } from "wouter";

export default function PrivacyPolicy() {
  const { data: config, isLoading } = useGetConfig();

  if (isLoading) {
    return <div className="p-8 space-y-4"><Skeleton className="h-8 w-48" /><Skeleton className="h-64 w-full" /></div>;
  }

  return (
    <div className="max-w-3xl mx-auto py-12 px-4">
      <Link href="/" className="text-primary no-underline hover:underline mb-8 inline-flex items-center gap-2">
        &larr; Back to Home
      </Link>
      
      <div className="prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>
        
        <p className="text-lg">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Interpretation and Definitions</h2>
        <h3 className="text-xl font-medium mt-6 mb-3">Interpretation</h3>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h3 className="text-xl font-medium mt-6 mb-3">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to {config?.storeName || "Our Store"}.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>You</strong> means the individual accessing or using the Service.</li>
          <li><strong>Personal Data</strong> means any information that relates to an identified or identifiable individual.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-medium mt-6 mb-3">Types of Data Collected</h3>
        
        <h4 className="text-lg font-medium mt-4 mb-2">Personal Data</h4>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Full Name</li>
          <li>Phone Number</li>
          <li>Address, City, State, Pincode, Country</li>
          <li>IP Address</li>
          <li>Landmark (optional)</li>
        </ul>

        <h4 className="text-lg font-medium mt-4 mb-2">Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Use of Your Personal Data</h2>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Orders</strong>: To fulfill and manage Your orders, payments, and deliveries through the Service.</li>
          <li><strong>To contact You</strong>: To contact You regarding your orders, updates, or other transactional communications.</li>
          <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
          <li><strong>To improve our Service</strong></li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Retention of Your Personal Data</h2>
        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Transfer of Your Personal Data</h2>
        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Disclosure of Your Personal Data</h2>
        <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Security of Your Personal Data</h2>
        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Changes to This Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc pl-6 space-y-2">
          {config?.contactEmail && <li>By email: {config.contactEmail}</li>}
          {config?.contactPhone && <li>By phone number: {config.contactPhone}</li>}
          {config?.contactAddress && <li>By visiting this page on our website: {config.contactAddress}</li>}
        </ul>
      </div>
    </div>
  );
}
